"""
Global State Management — Single source of truth for session state.

Inspired by Claude Code's bootstrap/state.ts pattern:
  - Identity & session tracking
  - Cost & usage tracking
  - Agent registry
  - Tool registry
  - Active trades & portfolio state
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from core.boot import BootMetrics
    from core.task import TaskManager
    from config.settings import AppConfig

# ── Trade State ─────────────────────────────────────────

@dataclass
class TradeSignal:
    """A trade signal generated by the analysis pipeline."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    symbol: str = ""
    timeframe: str = "1h"
    direction: str = "long"  # long | short
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit_1: float = 0.0
    take_profit_2: float = 0.0
    take_profit_3: float = 0.0
    confidence: float = 0.0       # 0-100
    risk_reward_ratio: float = 0.0
    expected_value: float = 0.0   # Kelly-weighted EV
    position_size_pct: float = 0.0
    strategy: str = ""
    reasoning: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    status: str = "pending"  # pending | approved | rejected | executed | closed

    # Analysis metadata
    atr: float = 0.0
    trend_strength: float = 0.0
    volume_score: float = 0.0
    support_level: float = 0.0
    resistance_level: float = 0.0


@dataclass
class ActiveTrade:
    """An open position being managed."""
    signal: TradeSignal
    entry_filled_price: float = 0.0
    entry_filled_time: Optional[datetime] = None
    quantity: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    trailing_stop: float = 0.0
    tp_hits: List[int] = field(default_factory=list)  # which TPs have been hit
    trajectory_id: str = ""  # hermes: linked trajectory for logging


@dataclass
class PortfolioState:
    """Current portfolio snapshot."""
    total_equity: float = 10000.0
    available_balance: float = 10000.0
    margin_used: float = 0.0
    open_positions: int = 0
    total_risk_pct: float = 0.0
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown_pct: float = 0.0
    active_trades: List[ActiveTrade] = field(default_factory=list)
    closed_trades: List[ActiveTrade] = field(default_factory=list)


# ── Global State ────────────────────────────────────────

class GlobalState:
    """
    Single source of truth for all session-scoped state.
    DO NOT ADD MORE STATE HERE — BE JUDICIOUS WITH GLOBAL STATE.
    """

    def __init__(self, config: "AppConfig"):
        # Identity
        self.session_id: str = uuid.uuid4().hex[:16]
        self.start_time: datetime = datetime.now(timezone.utc)

        # Config
        self.config: "AppConfig" = config

        # Boot metrics
        self.boot_metrics: Optional["BootMetrics"] = None

        # Agent registry (name → agent instance)
        self.agents: Dict[str, Any] = {}

        # Tool registry (name → tool instance)
        self.tools: Dict[str, Any] = {}

        # Coordinator
        self.coordinator: Any = None

        # Task manager
        self.task_manager: Optional["TaskManager"] = None

        # Portfolio & trading
        self.portfolio: PortfolioState = PortfolioState(
            total_equity=config.risk.initial_capital,
            available_balance=config.risk.initial_capital,
        )

        # Signal history
        self.signals: List[TradeSignal] = []

        # Market data cache
        self.market_data: Dict[str, Any] = {}

        # Stats
        self.total_analyses: int = 0
        self.total_signals: int = 0
        self.total_trades: int = 0


# ── Singleton Accessor ─────────────────────────────────

class _StateAccessor:
    _instance: Optional[GlobalState] = None

    def __call__(self) -> GlobalState:
        if self._instance is None:
            raise RuntimeError("GlobalState not initialized. Run boot sequence first.")
        return self._instance


get_state = _StateAccessor()
